FROM python:3.9-slim

WORKDIR /app

# Copy requirements first to leverage Docker cache
COPY requirements_dashboard.txt .  
RUN pip install --no-cache-dir -r requirements_dashboard.txt  

# Copy application code
COPY . .

# Expose the port that Streamlit runs on
EXPOSE 8080  

# Set environment variables
ENV PORT=8080  

# Start the Streamlit app
CMD streamlit run dashboard.py --server.port=$PORT --server.address=0.0.0.0 --server.enableCORS=false
